### ISSUE TITLE
Deploy to bintray.com

### ISSUE THREAD

**Issue by fniephaus** [peteruhnak/travis-deployment#1]
Have you seen https://github.com/hpi-swa/smalltalkCI/issues/146#issuecomment-223586660 yet? 😃

**Comment by peteruhnak** [comment]
I did actually. :)
But we have our own ssh server where I do some additional stuff (like bundling VMs for specific platforms and some other stuff… ) -- I am currently using this ( https://github.com/dynacase/dynacase/blob/master/scripts/deploy.sh ).

This repo is (at the moment) just for me for playing around (plus I am writing blog post on using SmalltalkCI + ssh).

**Comment by fniephaus** [comment]
Let me know if there's anything smalltalkCI can do for supporting your use cases.
We are slowly starting to work on deployment, so things might change/improve soon...
